-- DEPRECADO
--
-- Este archivo corresponde al cotizador anterior, donde cualquier visitante
-- podía modificar vehículos. NO lo ejecutes para la versión nueva.
--
-- Usa:
--   SUPABASE_V2_SETUP.sql
--
-- Ese script migra la tabla vehiculos, agrega autenticación, roles, clientes,
-- permutas, seguimientos, cotizaciones, auditoría y catálogo público seguro.
