-- ================================================================
-- AUTOSALE MOTORS · PATCH V2.4
-- Ejecutar UNA VEZ (es idempotente) en Supabase > SQL Editor.
-- Añade edición/borrado recuperable, Bs completos, archivo de clientes,
-- historial de reasignaciones y soporte Realtime para CRM.
-- ================================================================

-- 1) Campos nuevos ------------------------------------------------
alter table public.clientes
  add column if not exists archived_at timestamptz;

alter table public.seguimientos
  add column if not exists deleted_at timestamptz;

alter table public.cotizaciones
  add column if not exists cuota_inicial_bs numeric(14,2) not null default 0,
  add column if not exists monto_financiado_bs numeric(14,2) not null default 0,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists deleted_at timestamptz;

create index if not exists idx_clientes_archived_at on public.clientes (archived_at);
create index if not exists idx_seguimientos_deleted_at on public.seguimientos (deleted_at);
create index if not exists idx_cotizaciones_deleted_at on public.cotizaciones (deleted_at);

-- Completar Bs en cotizaciones antiguas usando el tipo de cambio central
update public.cotizaciones q
set
  cuota_inicial_bs = case when coalesce(q.cuota_inicial_bs,0)=0 then round(q.cuota_inicial_usd * s.tipo_cambio) else q.cuota_inicial_bs end,
  monto_financiado_bs = case when coalesce(q.monto_financiado_bs,0)=0 then round(q.monto_financiado_usd * s.tipo_cambio) else q.monto_financiado_bs end
from public.app_settings s
where s.id=1
  and (coalesce(q.cuota_inicial_bs,0)=0 or coalesce(q.monto_financiado_bs,0)=0);

-- 2) updated_at automático ----------------------------------------
drop trigger if exists trg_clientes_updated_at on public.clientes;
create trigger trg_clientes_updated_at
before update on public.clientes
for each row execute function public.set_generic_updated_at();

drop trigger if exists trg_permutas_updated_at on public.cliente_permutas;
create trigger trg_permutas_updated_at
before update on public.cliente_permutas
for each row execute function public.set_generic_updated_at();

drop trigger if exists trg_seguimientos_updated_at on public.seguimientos;
create trigger trg_seguimientos_updated_at
before update on public.seguimientos
for each row execute function public.set_generic_updated_at();

drop trigger if exists trg_cotizaciones_updated_at on public.cotizaciones;
create trigger trg_cotizaciones_updated_at
before update on public.cotizaciones
for each row execute function public.set_generic_updated_at();

-- 3) Historial de reasignación ------------------------------------
create table if not exists public.cliente_asignaciones (
  id bigint generated by default as identity primary key,
  cliente_id uuid not null references public.clientes(id) on delete cascade,
  anterior_id uuid references public.profiles(id) on delete set null,
  nuevo_id uuid references public.profiles(id) on delete set null,
  cambiado_por uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);
create index if not exists idx_cliente_asignaciones_cliente on public.cliente_asignaciones (cliente_id, created_at desc);

create or replace function public.log_cliente_reasignacion()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.asesor_id is distinct from new.asesor_id then
    insert into public.cliente_asignaciones(cliente_id, anterior_id, nuevo_id, cambiado_por)
    values(new.id, old.asesor_id, new.asesor_id, auth.uid());
  end if;
  return new;
end;
$$;

drop trigger if exists trg_cliente_reasignacion on public.clientes;
create trigger trg_cliente_reasignacion
after update of asesor_id on public.clientes
for each row execute function public.log_cliente_reasignacion();

alter table public.cliente_asignaciones enable row level security;
drop policy if exists cliente_asignaciones_select on public.cliente_asignaciones;
create policy cliente_asignaciones_select on public.cliente_asignaciones
for select to authenticated
using (
  public.is_admin()
  or exists (
    select 1 from public.clientes c
    where c.id = cliente_id and c.asesor_id = auth.uid()
  )
);
revoke all on table public.cliente_asignaciones from anon;
grant select on table public.cliente_asignaciones to authenticated;

-- 4) Al marcar vendido, cerrar seguimientos vigentes --------------
create or replace function public.close_followups_when_sold()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.estado = 'vendido' and old.estado is distinct from new.estado then
    update public.seguimientos
    set estado='completado', completado_at=coalesce(completado_at, now())
    where cliente_id=new.id
      and estado='pendiente'
      and deleted_at is null;
  end if;
  return new;
end;
$$;

drop trigger if exists trg_close_followups_when_sold on public.clientes;
create trigger trg_close_followups_when_sold
after update of estado on public.clientes
for each row execute function public.close_followups_when_sold();

-- 5) Realtime para el CRM -----------------------------------------
do $$
begin
  alter publication supabase_realtime add table public.clientes;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.seguimientos;
exception when duplicate_object then null;
end $$;

do $$
begin
  alter publication supabase_realtime add table public.cotizaciones;
exception when duplicate_object then null;
end $$;

-- Fin del patch V2.4
